version: '3.8'

services:
  db:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: ponto
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  app:
   build:
     dockerfile: Dockerfile
     context: .
   ports:
       - 8080:8080
   depends_on:
       - db
   pull_policy: always
   restart: on-failure
